services:
  db:
    image: 3m-mysql:1.0
    command:
      --bind-address=0.0.0.0
    environment:
      MYSQL_ROOT_PASSWORD: pass123
    volumes:
      - db:/var/lib/mysql
    container_name: 3msql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysql", "-u", "3madmin", "-pmypass111", "-e", "show databases;"] 
      interval: 20s
      retries: 5
      start_period: 360s
      timeout: 10s
  
  api:
    image: 3m-api:1.0
    container_name: 3mapi
    depends_on:
      db:
        condition: service_healthy
        restart: true
    ports: 
      - "8080:8080"

  gui:
    image: 3m-gui:1.0
    container_name: 3mgui
    ports:
      - "80:80"

volumes:
  db:
