services:
  db:
    image: mysql/mysql-server
    command:
      --bind-address=0.0.0.0
    environment:
      MYSQL_ROOT_PASSWORD: pass123
    volumes:
      - db:/var/lib/mysql
    container_name: 3msql
    ports:
      - "3306:3306"

volumes:
  db:
